import { ProcessDefinition } from "@/components/shared/process-flow";

/* ================================================================== */
/* 1. RECEPCIÓN CLIENTES - VISITA (Walk-in)                            */
/* ================================================================== */
export const recepcionVisitaProcess: ProcessDefinition = {
  id: "recepcion-visita",
  name: "Recepción Clientes — Visita",
  description: "Proceso de atención cuando un cliente visita el estudio jurídico",
  agents: [
    {
      id: "secretaria",
      name: "Secretaria",
      role: "secretaria",
      color: "blue",
      description: "Recibe al cliente, revisa agenda y coordina con abogado",
    },
    {
      id: "abogado",
      name: "Abogado",
      role: "abogado",
      color: "green",
      description: "Atiende al cliente, analiza la causa y entrega propuesta",
    },
  ],
  steps: [
    {
      id: "v-start",
      label: "Cliente visita estudio",
      description: "Un cliente llega al estudio jurídico sin cita previa o con cita agendada.",
      agentId: "secretaria",
      type: "start",
      nextSteps: [{ targetId: "v-recepcion" }],
    },
    {
      id: "v-recepcion",
      label: "Recepción y revisión de agenda",
      description: "La secretaria recibe al cliente y revisa si el abogado solicitado está disponible en la agenda.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [
        { label: "Abogado disponible", targetId: "v-derivar" },
        { label: "Abogado ocupado", targetId: "v-turno" },
      ],
    },
    {
      id: "v-turno",
      label: "¿Ofrecer abogado de turno?",
      description: "Si el abogado no está, se ofrece el servicio del abogado de turno disponible.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Acepta", targetId: "v-derivar" },
        { label: "No acepta", targetId: "v-agendar-check" },
      ],
    },
    {
      id: "v-derivar",
      label: "Derivar a Abogado",
      description: "Se avisa al abogado solicitado o de turno y se deriva al cliente.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "v-atencion" }],
    },
    {
      id: "v-atencion",
      label: "Atención e ingreso en base de datos",
      description: "El abogado atiende al cliente, recaba información del caso e ingresa datos en el sistema.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "v-analisis" }],
    },
    {
      id: "v-analisis",
      label: "Análisis de causa y propuesta",
      description: "Se analiza la causa, su rentabilidad y se entrega una propuesta al cliente en el momento.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "v-acepta" }],
    },
    {
      id: "v-acepta",
      label: "¿Cliente acepta propuesta?",
      description: "El cliente evalúa la propuesta. Si rechaza, se gestionan objeciones (valor, plazo o estrategia).",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "v-entrega" },
        { label: "Plantea objeciones", targetId: "v-objeciones" },
      ],
    },
    {
      id: "v-objeciones",
      label: "Gestionar objeciones",
      description: "Según la objeción: por valor se ofrece pago diferente, por plazo se explican plazos judiciales, por estrategia se ofrecen alternativas.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "v-acepta" }],
    },
    {
      id: "v-entrega",
      label: "Entrega propuesta a Secretaria",
      description: "Se entrega la propuesta aceptada y se pasa a secretaria para el agendamiento correspondiente.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "v-agendar" }],
    },
    {
      id: "v-agendar-check",
      label: "¿Acepta agendamiento?",
      description: "Se consulta al cliente si desea agendar una cita para otro momento.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "v-agendar" },
        { label: "No", targetId: "v-end" },
      ],
    },
    {
      id: "v-agendar",
      label: "Agendar cita",
      description: "Se agenda la reunión con el cliente en el sistema de calendario.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "v-end" }],
    },
    {
      id: "v-end",
      label: "Fin",
      description: "Proceso de recepción presencial completado.",
      agentId: "secretaria",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 2. RECEPCIÓN CLIENTES - TELÉFONO                                    */
/* ================================================================== */
export const recepcionTelefonoProcess: ProcessDefinition = {
  id: "recepcion-telefono",
  name: "Recepción Clientes — Teléfono",
  description: "Proceso de atención cuando un cliente llama por teléfono",
  agents: [
    {
      id: "secretaria",
      name: "Secretaria",
      role: "secretaria",
      color: "blue",
      description: "Atiende llamada, verifica disponibilidad de abogado y gestiona agendamiento",
    },
  ],
  steps: [
    {
      id: "t-start",
      label: "Llamada entrante",
      description: "Se recibe una llamada telefónica en el estudio.",
      agentId: "secretaria",
      type: "start",
      nextSteps: [{ targetId: "t-atencion" }],
    },
    {
      id: "t-atencion",
      label: "Atención según protocolo",
      description: "La secretaria atiende la llamada siguiendo el protocolo telefónico establecido.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-busca" }],
    },
    {
      id: "t-busca",
      label: "¿A quién busca?",
      description: "Se determina si busca un abogado específico o es un cliente nuevo.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Abogado específico", targetId: "t-disponible" },
        { label: "Cliente nuevo", targetId: "t-ficha" },
      ],
    },
    {
      id: "t-disponible",
      label: "Verificar disponibilidad",
      description: "Se verifica si el abogado solicitado se encuentra disponible.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [
        { label: "Disponible", targetId: "t-transferir" },
        { label: "No disponible", targetId: "t-espera" },
      ],
    },
    {
      id: "t-transferir",
      label: "Transferir llamada",
      description: "Se transfiere la llamada al abogado en 2 pasos según protocolo.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-end-contactado" }],
    },
    {
      id: "t-espera",
      label: "¿Esperar o devolver llamada?",
      description: "Se pregunta al cliente si prefiere esperar o que le devuelvan la llamada.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Espera", targetId: "t-retomar" },
        { label: "Devolver", targetId: "t-datos-llamada" },
      ],
    },
    {
      id: "t-retomar",
      label: "Retomar cada 40 segundos",
      description: "Se retoma comunicación con el cliente cada 40 segundos hasta que el abogado se desocupe.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-transferir" }],
    },
    {
      id: "t-datos-llamada",
      label: "Tomar datos y horario",
      description: "Se registran los datos del cliente y el horario para devolver la llamada.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-contactar" }],
    },
    {
      id: "t-contactar",
      label: "Contactar en horario acordado",
      description: "Se contacta al cliente en el horario convenido.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-end-contactado" }],
    },
    {
      id: "t-ficha",
      label: "Completar ficha de cliente",
      description: "Se toman datos del cliente nuevo y se completa la ficha en el sistema.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-acepta-reunion" }],
    },
    {
      id: "t-acepta-reunion",
      label: "¿Acepta reunión?",
      description: "Se consulta si el cliente acepta agendar una reunión en el estudio.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "t-agendar" },
        { label: "No", targetId: "t-recontacto" },
      ],
    },
    {
      id: "t-agendar",
      label: "Revisar Zoho y agendar",
      description: "Se revisa disponibilidad en Zoho y se agenda la reunión.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-end-contactado" }],
    },
    {
      id: "t-recontacto",
      label: "Recontactar en 48 horas",
      description: "Se indica al cliente que se le volverá a contactar en 48 horas.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "t-end-no" }],
    },
    {
      id: "t-end-contactado",
      label: "Contactado",
      description: "Cliente contactado exitosamente.",
      agentId: "secretaria",
      type: "end",
    },
    {
      id: "t-end-no",
      label: "No contactado",
      description: "Cliente no pudo ser contactado, se reintentará.",
      agentId: "secretaria",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 3. SEGUIMIENTO DE PROPUESTAS                                        */
/* ================================================================== */
export const seguimientoPropuestasProcess: ProcessDefinition = {
  id: "seguimiento-propuestas",
  name: "Seguimiento de Propuestas",
  description: "Proceso de creación, envío y seguimiento de propuestas de honorarios",
  agents: [
    {
      id: "abogado-jefe",
      name: "Abogado Jefe",
      role: "abogado_jefe",
      color: "purple",
      description: "Define montos, medios de pago y estrategia de la propuesta",
    },
    {
      id: "abogado",
      name: "Abogado",
      role: "abogado",
      color: "green",
      description: "Entrevista cliente, redacta propuesta y realiza seguimiento",
    },
    {
      id: "administracion",
      name: "Administración",
      role: "administracion",
      color: "amber",
      description: "Recibe propuesta, archiva datos y realiza seguimiento de 72 horas",
    },
  ],
  steps: [
    {
      id: "sp-start",
      label: "Entrevista a cliente",
      description: "El abogado realiza la entrevista con el cliente y analiza el plan de trabajo de la causa.",
      agentId: "abogado",
      type: "start",
      nextSteps: [{ targetId: "sp-requiere-jefe" }],
    },
    {
      id: "sp-requiere-jefe",
      label: "¿Requiere al Abogado Jefe?",
      description: "Se determina si la propuesta necesita aprobación del Abogado Jefe.",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "sp-reunion-jefe" },
        { label: "No", targetId: "sp-redactar" },
      ],
    },
    {
      id: "sp-reunion-jefe",
      label: "Reunión con Abogado Jefe",
      description: "El Abogado Jefe define montos, medio de pago y estrategia de la propuesta.",
      agentId: "abogado-jefe",
      type: "task",
      nextSteps: [{ targetId: "sp-redactar" }],
    },
    {
      id: "sp-redactar",
      label: "Redactar y enviar propuesta",
      description: "El abogado redacta la propuesta y la envía por correo al cliente con copia a Administración.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "sp-admin-recibe" }],
    },
    {
      id: "sp-admin-recibe",
      label: "Administración recibe y archiva",
      description: "Administración recibe la propuesta, incluye datos en el archivo de seguimiento. Se envía a equipo de abogados si hay modificaciones.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "sp-contacto-72" }],
    },
    {
      id: "sp-contacto-72",
      label: "Contacto a las 72 horas",
      description: "Administración contacta al cliente a las 72 horas de entregada la propuesta para consultar recepción, lectura y conformidad.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "sp-cliente-lee" }],
    },
    {
      id: "sp-cliente-lee",
      label: "¿Cliente leyó y da conformidad?",
      description: "Se verifica si el cliente recibió, leyó y está conforme con la propuesta.",
      agentId: "administracion",
      type: "decision",
      nextSteps: [
        { label: "Sí, acepta", targetId: "sp-agendar-firma" },
        { label: "No responde", targetId: "sp-reintento" },
      ],
    },
    {
      id: "sp-agendar-firma",
      label: "Agendar firma de contrato",
      description: "Se agenda reunión con el cliente en base a disponibilidad del abogado para firmar contrato.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "sp-end" }],
    },
    {
      id: "sp-reintento",
      label: "Reintento de contacto",
      description: "Se contacta 3 veces en diferentes horarios y se envía correo electrónico informando plazo de caducidad de la propuesta.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "sp-end" }],
    },
    {
      id: "sp-end",
      label: "Fin",
      description: "Proceso de seguimiento de propuesta completado.",
      agentId: "administracion",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 4. CONTRATO Y MANDATO JUDICIAL                                      */
/* ================================================================== */
export const contratoMandatoProcess: ProcessDefinition = {
  id: "contrato-mandato",
  name: "Contrato y Mandato Judicial",
  description: "Proceso de formalización del contrato y mandato con el cliente",
  agents: [
    {
      id: "abogado",
      name: "Abogado",
      role: "abogado",
      color: "green",
      description: "Aprueba propuesta, verifica contrato y envía mandato a notaría",
    },
    {
      id: "administracion",
      name: "Administración",
      role: "administracion",
      color: "amber",
      description: "Confecciona contrato, sube a intranet y escanea documentos firmados",
    },
    {
      id: "notaria",
      name: "Notaría",
      role: "procurador",
      color: "purple",
      description: "Gestiona firma de mandato y documentos notariales",
    },
  ],
  steps: [
    {
      id: "cm-start",
      label: "Acuerdo con cliente",
      description: "El cliente llega a acuerdo con el abogado y se aprueba la propuesta.",
      agentId: "abogado",
      type: "start",
      nextSteps: [{ targetId: "cm-informa" }],
    },
    {
      id: "cm-informa",
      label: "Informar a Administración",
      description: "El abogado informa a Administración del cierre de contrato con el cliente.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "cm-datos-check" }],
    },
    {
      id: "cm-datos-check",
      label: "¿Datos completos?",
      description: "Se verifica si se tienen todos los datos necesarios para confeccionar el contrato.",
      agentId: "administracion",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "cm-confeccionar" },
        { label: "No", targetId: "cm-devolver" },
      ],
    },
    {
      id: "cm-devolver",
      label: "Devolver a Abogado",
      description: "Se devuelve la propuesta al abogado para completar los datos faltantes.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "cm-datos-check" }],
    },
    {
      id: "cm-confeccionar",
      label: "Confeccionar contrato",
      description: "Se confecciona el contrato del cliente en atención a la propuesta enviada.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "cm-enviar-vb" }],
    },
    {
      id: "cm-enviar-vb",
      label: "Enviar contrato para VB",
      description: "Se envía el contrato al abogado para su visto bueno y verificación.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "cm-verificar" }],
    },
    {
      id: "cm-verificar",
      label: "Verificar contrato",
      description: "El abogado verifica que el contrato sea correcto en todos sus términos.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "cm-correcto" }],
    },
    {
      id: "cm-correcto",
      label: "¿Está correcto?",
      description: "Decisión sobre si el contrato está correcto o necesita modificaciones.",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "cm-subir" },
        { label: "No", targetId: "cm-modificar" },
      ],
    },
    {
      id: "cm-modificar",
      label: "Realizar modificaciones",
      description: "Se realizan las modificaciones y se devuelve a Administración.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "cm-confeccionar" }],
    },
    {
      id: "cm-subir",
      label: "Subir a intranet y citar",
      description: "Se sube el contrato a la intranet para conocimiento público y se cita al cliente para firma.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "cm-mandato" }],
    },
    {
      id: "cm-mandato",
      label: "Enviar mandato a Notaría",
      description: "El abogado envía el mandato a la notaría para firma del cliente.",
      agentId: "notaria",
      type: "subprocess",
      nextSteps: [{ targetId: "cm-escanear" }],
    },
    {
      id: "cm-escanear",
      label: "Escanear y subir documento",
      description: "Se escanea el documento firmado y se sube a la intranet. Se confirman todos los documentos en línea.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "cm-end" }],
    },
    {
      id: "cm-end",
      label: "Documentos confirmados",
      description: "Todos los documentos están en línea y el proceso está completo.",
      agentId: "administracion",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 5. DOCUMENTOS NOTARIALES                                            */
/* ================================================================== */
export const documentosNotarialesProcess: ProcessDefinition = {
  id: "documentos-notariales",
  name: "Documentos Notariales",
  description: "Proceso de gestión de documentos notariales con firma en notaría",
  agents: [
    {
      id: "gerente-legal",
      name: "Gerente Legal",
      role: "gerente_legal",
      color: "rose",
      description: "Ingresa cliente y asigna abogado a cargo del documento",
    },
    {
      id: "abogado",
      name: "Abogado",
      role: "abogado",
      color: "green",
      description: "Solicita antecedentes, redacta documento y confirma estado con cliente",
    },
    {
      id: "notaria",
      name: "Notaría",
      role: "procurador",
      color: "purple",
      description: "Recepciona y firma documentos notariales",
    },
    {
      id: "cliente",
      name: "Cliente",
      role: "cliente_portal",
      color: "cyan",
      description: "Firma documento en notaría y confirma al abogado",
    },
  ],
  steps: [
    {
      id: "dn-start",
      label: "Ingreso de cliente",
      description: "El Gerente Legal ingresa al cliente y entrega la información al abogado a cargo.",
      agentId: "gerente-legal",
      type: "start",
      nextSteps: [{ targetId: "dn-antecedentes" }],
    },
    {
      id: "dn-antecedentes",
      label: "Solicitar antecedentes",
      description: "El abogado solicita todos los antecedentes necesarios al cliente.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "dn-check-antecedentes" }],
    },
    {
      id: "dn-check-antecedentes",
      label: "¿Están todos los antecedentes?",
      description: "Se verifica si se recibieron todos los antecedentes necesarios.",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "dn-redactar" },
        { label: "No", targetId: "dn-antecedentes" },
      ],
    },
    {
      id: "dn-redactar",
      label: "Redacción de documento",
      description: "El abogado redacta el documento solicitado con todos los antecedentes.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "dn-envio-notaria" }],
    },
    {
      id: "dn-envio-notaria",
      label: "Envío a Notaría",
      description: "Se envía el documento redactado a la notaría para su procesamiento.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "dn-recepcion" }],
    },
    {
      id: "dn-recepcion",
      label: "Notaría confirma recepción",
      description: "La notaría confirma la recepción del documento y procede con la firma.",
      agentId: "notaria",
      type: "task",
      nextSteps: [{ targetId: "dn-firma-notaria" }],
    },
    {
      id: "dn-firma-notaria",
      label: "Notaría firma documento",
      description: "El notario firma el documento oficial.",
      agentId: "notaria",
      type: "task",
      nextSteps: [{ targetId: "dn-contacto-cliente" }],
    },
    {
      id: "dn-contacto-cliente",
      label: "Contactar cliente",
      description: "Se intenta contactar al cliente en horario de 10, 13 y 17 horas para informar que el documento está disponible.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "dn-firma-cliente" }],
    },
    {
      id: "dn-firma-cliente",
      label: "Cliente firma en Notaría",
      description: "El cliente acude a la notaría y firma el documento.",
      agentId: "cliente",
      type: "task",
      nextSteps: [{ targetId: "dn-archivar" }],
    },
    {
      id: "dn-archivar",
      label: "Archivar en carpeta cliente",
      description: "El documento firmado se ingresa a la carpeta del cliente y se informa al Gerente Legal.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "dn-end" }],
    },
    {
      id: "dn-end",
      label: "Fin",
      description: "Proceso de documentos notariales completado.",
      agentId: "gerente-legal",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 6. RESPUESTA A CORREOS ABOGADOS                                     */
/* ================================================================== */
export const respuestaCorreosProcess: ProcessDefinition = {
  id: "respuesta-correos",
  name: "Respuesta a Correos de Abogados",
  description: "Proceso de gestión y respuesta de correos de clientes con SLA de 24-48 horas",
  agents: [
    {
      id: "abogado",
      name: "Abogado",
      role: "abogado",
      color: "green",
      description: "Analiza correo, recaba información, redacta respuesta y confirma recepción",
    },
    {
      id: "abogado-jefe",
      name: "Abogado Jefe",
      role: "abogado_jefe",
      color: "purple",
      description: "Apoya en respuestas complejas y gestiona retrasos en SLA",
    },
  ],
  steps: [
    {
      id: "rc-start",
      label: "Cliente contacta al abogado",
      description: "Un cliente contacta al abogado por correo electrónico o teléfono.",
      agentId: "abogado",
      type: "start",
      nextSteps: [{ targetId: "rc-medio" }],
    },
    {
      id: "rc-medio",
      label: "¿Por qué medio?",
      description: "Se determina el medio de contacto: teléfono o correo.",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "Teléfono", targetId: "rc-protocolo" },
        { label: "Correo", targetId: "rc-analizar" },
      ],
    },
    {
      id: "rc-protocolo",
      label: "Contestar según protocolo",
      description: "El abogado contesta al cliente según el protocolo telefónico establecido.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rc-end" }],
    },
    {
      id: "rc-analizar",
      label: "Analizar correo",
      description: "El abogado analiza el contenido del correo y planea la respuesta idónea.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rc-requiere-jefe" }],
    },
    {
      id: "rc-requiere-jefe",
      label: "¿Requiere Abogado Jefe?",
      description: "Se determina si la respuesta necesita el apoyo o VB del Abogado Jefe.",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "No", targetId: "rc-redactar" },
        { label: "Sí", targetId: "rc-jefe" },
      ],
    },
    {
      id: "rc-jefe",
      label: "Abogado Jefe apoya respuesta",
      description: "El Abogado Jefe recibe la solicitud de ayuda y se redacta en conjunto la respuesta con su VB.",
      agentId: "abogado-jefe",
      type: "task",
      nextSteps: [{ targetId: "rc-redactar" }],
    },
    {
      id: "rc-redactar",
      label: "Redactar y enviar respuesta",
      description: "El abogado redacta el correo de respuesta y lo envía en un plazo no mayor a 24 horas.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rc-confirmar" }],
    },
    {
      id: "rc-confirmar",
      label: "Confirmar recepción",
      description: "Se confirma vía telefónica con el cliente la recepción del correo.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rc-end" }],
    },
    {
      id: "rc-end",
      label: "Fin",
      description: "Proceso de respuesta a correos completado.",
      agentId: "abogado",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 7. PROCESO DE COBRANZA                                              */
/* ================================================================== */
export const procesoCobranzaProcess: ProcessDefinition = {
  id: "proceso-cobranza",
  name: "Proceso de Cobranza",
  description: "Proceso de cobro de facturas con escalamiento a cobranza judicial",
  agents: [
    {
      id: "secretaria",
      name: "Secretaria",
      role: "secretaria",
      color: "blue",
      description: "Realiza llamadas de cobro, contacto pre-vencimiento y gestión de cheques",
    },
    {
      id: "jefe-cobranza",
      name: "Jefe de Cobranza",
      role: "jefe_cobranza",
      color: "rose",
      description: "Gestiona casos escalados, cobranza judicial y terminación de relaciones",
    },
  ],
  steps: [
    {
      id: "pc-start",
      label: "Inicio cobranza",
      description: "Se inicia el proceso de cobranza para un cliente con facturas pendientes.",
      agentId: "secretaria",
      type: "start",
      nextSteps: [{ targetId: "pc-cheques" }],
    },
    {
      id: "pc-cheques",
      label: "¿Entrega cheques?",
      description: "Se verifica si el cliente entrega cheques al momento de contratar.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "pc-cheques-pendientes" },
        { label: "No", targetId: "pc-contacto-pre" },
      ],
    },
    {
      id: "pc-cheques-pendientes",
      label: "Pasa a cobranza de cheques",
      description: "Se gestionan los cheques del cliente como instrumento de cobro.",
      agentId: "jefe-cobranza",
      type: "task",
      nextSteps: [{ targetId: "pc-end" }],
    },
    {
      id: "pc-contacto-pre",
      label: "Contacto 5 días antes",
      description: "Se contacta al cliente 5 días antes del vencimiento de la factura.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "pc-contesta1" }],
    },
    {
      id: "pc-contesta1",
      label: "¿Cliente contesta?",
      description: "Se verifica si el cliente contesta las llamadas en horarios de 11, 15 y 18 horas.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "pc-informar" },
        { label: "No", targetId: "pc-insistir" },
      ],
    },
    {
      id: "pc-informar",
      label: "Informar vencimiento y solicitar pago",
      description: "Se informa al cliente del vencimiento y se solicita el pago.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "pc-paga1" }],
    },
    {
      id: "pc-paga1",
      label: "¿Paga?",
      description: "Se verifica si el cliente realiza el pago.",
      agentId: "secretaria",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "pc-deposito" },
        { label: "No", targetId: "pc-dia-vencimiento" },
      ],
    },
    {
      id: "pc-deposito",
      label: "Generar depósito y cancelar cuota",
      description: "Se genera el depósito de pago y se cancela la cuota correspondiente.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "pc-end" }],
    },
    {
      id: "pc-dia-vencimiento",
      label: "Contactar día de vencimiento",
      description: "Se contacta al cliente el día del vencimiento.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "pc-escalar" }],
    },
    {
      id: "pc-insistir",
      label: "Enviar correo e insistir 3 días",
      description: "Se envía correo y se insiste por llamado durante 3 días seguidos.",
      agentId: "secretaria",
      type: "task",
      nextSteps: [{ targetId: "pc-escalar" }],
    },
    {
      id: "pc-escalar",
      label: "Escalar a Jefe Cobranza",
      description: "El caso pasa al Jefe de Cobranza para suspensión de servicio e inicio de cobranza judicial.",
      agentId: "jefe-cobranza",
      type: "task",
      nextSteps: [{ targetId: "pc-cese" }],
    },
    {
      id: "pc-cese",
      label: "Enviar correo de cese",
      description: "Se envía correo informando cese de servicio y se intenta contacto telefónico por 1 semana.",
      agentId: "jefe-cobranza",
      type: "task",
      nextSteps: [{ targetId: "pc-respuesta" }],
    },
    {
      id: "pc-respuesta",
      label: "¿Hay respuesta?",
      description: "Se evalúa si el cliente responde al aviso de cese.",
      agentId: "jefe-cobranza",
      type: "decision",
      nextSteps: [
        { label: "Sí, pagará", targetId: "pc-plazo48" },
        { label: "No responde", targetId: "pc-terminar" },
      ],
    },
    {
      id: "pc-plazo48",
      label: "Agendar plazo 48 horas",
      description: "Se informa plazo de 48 horas para regularizar el pago.",
      agentId: "jefe-cobranza",
      type: "task",
      nextSteps: [{ targetId: "pc-end" }],
    },
    {
      id: "pc-terminar",
      label: "Terminar relación contractual",
      description: "Se informa al cliente del término de la relación contractual y se ordena al Gerente Legal suspender tramitación.",
      agentId: "jefe-cobranza",
      type: "task",
      nextSteps: [{ targetId: "pc-end" }],
    },
    {
      id: "pc-end",
      label: "Fin",
      description: "Proceso de cobranza completado.",
      agentId: "jefe-cobranza",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 8. CAUSAS JPL (Juzgado Policía Local)                               */
/* ================================================================== */
export const causasJPLProcess: ProcessDefinition = {
  id: "causas-jpl",
  name: "Proceso Causas JPL",
  description: "Proceso de gestión de causas en Juzgado de Policía Local",
  agents: [
    {
      id: "agente-comercial",
      name: "Agente Comercial",
      role: "agente_comercial",
      color: "teal",
      description: "Ingresa la causa, verifica requisitos y gestiona comisiones",
    },
    {
      id: "administracion",
      name: "Administración",
      role: "administracion",
      color: "amber",
      description: "Contacta clientes, agenda citas y corrobora recepción de propuestas",
    },
    {
      id: "abogado-jpl",
      name: "Abogado JPL",
      role: "abogado",
      color: "green",
      description: "Recibe datos, agenda cita con cliente, entrega propuesta y gestiona contrato",
    },
  ],
  steps: [
    {
      id: "jpl-start",
      label: "Ingreso de causa",
      description: "El agente comercial ingresa una nueva causa y analiza los requisitos.",
      agentId: "agente-comercial",
      type: "start",
      nextSteps: [{ targetId: "jpl-requisitos" }],
    },
    {
      id: "jpl-requisitos",
      label: "¿Cumple requisitos?",
      description: "Se verifica si la causa cumple con los requisitos para ser tomada.",
      agentId: "agente-comercial",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "jpl-contacto" },
        { label: "No", targetId: "jpl-descarta" },
      ],
    },
    {
      id: "jpl-descarta",
      label: "Descartar causa",
      description: "El agente comercial descarta la causa por no cumplir requisitos.",
      agentId: "agente-comercial",
      type: "task",
      nextSteps: [{ targetId: "jpl-end" }],
    },
    {
      id: "jpl-contacto",
      label: "Contacto telefónico con cliente",
      description: "Administración realiza el contacto telefónico con el cliente potencial.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "jpl-interesa" }],
    },
    {
      id: "jpl-interesa",
      label: "¿Cliente se interesa?",
      description: "Se evalúa si el cliente muestra interés en el servicio.",
      agentId: "administracion",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "jpl-datos" },
        { label: "No", targetId: "jpl-end" },
      ],
    },
    {
      id: "jpl-datos",
      label: "Entregar datos a Abogado",
      description: "Se entregan los datos del cliente al Abogado JPL y se agenda una cita.",
      agentId: "abogado-jpl",
      type: "task",
      nextSteps: [{ targetId: "jpl-presenta" }],
    },
    {
      id: "jpl-presenta",
      label: "¿Cliente se presenta?",
      description: "Se verifica si el cliente se presenta a la cita agendada.",
      agentId: "abogado-jpl",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "jpl-propuesta" },
        { label: "No", targetId: "jpl-reagendar" },
      ],
    },
    {
      id: "jpl-reagendar",
      label: "Reagendar cita",
      description: "Se contacta al cliente y se agenda una nueva cita.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "jpl-presenta" }],
    },
    {
      id: "jpl-propuesta",
      label: "Entregar propuesta de honorarios",
      description: "El abogado entrega propuesta de honorarios física y por correo. Plazo de 48 horas para aceptar.",
      agentId: "abogado-jpl",
      type: "task",
      nextSteps: [{ targetId: "jpl-acepta" }],
    },
    {
      id: "jpl-acepta",
      label: "¿Acepta propuesta?",
      description: "Se verifica si el cliente acepta la propuesta dentro del plazo de 48 horas.",
      agentId: "abogado-jpl",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "jpl-contrato" },
        { label: "No", targetId: "jpl-end" },
      ],
    },
    {
      id: "jpl-contrato",
      label: "Entregar contrato y derivar a pago",
      description: "Se entrega el contrato al cliente y se deriva a Administración para gestionar el pago.",
      agentId: "abogado-jpl",
      type: "task",
      nextSteps: [{ targetId: "jpl-inicio-causa" }],
    },
    {
      id: "jpl-inicio-causa",
      label: "Recepcionar contrato e iniciar causa",
      description: "Se recepciona el contrato con el pago inicial y se da inicio a la causa judicial.",
      agentId: "administracion",
      type: "task",
      nextSteps: [{ targetId: "jpl-comision" }],
    },
    {
      id: "jpl-comision",
      label: "Gestionar comisión",
      description: "Se informa al agente comercial y se gestiona el pago de comisión.",
      agentId: "agente-comercial",
      type: "task",
      nextSteps: [{ targetId: "jpl-end" }],
    },
    {
      id: "jpl-end",
      label: "Fin",
      description: "Proceso de causas JPL completado.",
      agentId: "agente-comercial",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 9. REVISIÓN DIARIA DE CAUSAS                                        */
/* ================================================================== */
export const revisionCausasProcess: ProcessDefinition = {
  id: "revision-causas",
  name: "Revisión Diaria de Causas",
  description: "Proceso diario de revisión de expedientes electrónicos de todas las causas",
  agents: [
    {
      id: "abogado",
      name: "Abogado",
      role: "abogado",
      color: "green",
      description: "Entrega listado de causas, realiza trámites y contacta clientes con novedades",
    },
    {
      id: "procurador",
      name: "Procurador",
      role: "procurador",
      color: "purple",
      description: "Revisa expedientes electrónicos, informa movimientos y presenta gestiones en tribunal",
    },
  ],
  steps: [
    {
      id: "rv-start",
      label: "Revisión de causas",
      description: "Se inicia la revisión diaria del listado de causas abiertas.",
      agentId: "abogado",
      type: "start",
      nextSteps: [{ targetId: "rv-listado" }],
    },
    {
      id: "rv-listado",
      label: "Entregar listado a Procurador",
      description: "El abogado entrega el listado de causas al Procurador para revisión en el sistema.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rv-revisar" }],
    },
    {
      id: "rv-revisar",
      label: "Revisar expedientes electrónicos",
      description: "El procurador revisa el expediente electrónico de todas las causas entregadas.",
      agentId: "procurador",
      type: "task",
      nextSteps: [{ targetId: "rv-movimiento" }],
    },
    {
      id: "rv-movimiento",
      label: "¿Causa con movimiento?",
      description: "Se determina si la causa tiene nuevas gestiones o movimientos.",
      agentId: "procurador",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "rv-informar" },
        { label: "No", targetId: "rv-sin-mov" },
      ],
    },
    {
      id: "rv-sin-mov",
      label: "Informar sin movimiento",
      description: "Se informa al abogado que no existen nuevas gestiones en la causa.",
      agentId: "procurador",
      type: "task",
      nextSteps: [{ targetId: "rv-end" }],
    },
    {
      id: "rv-informar",
      label: "Informar movimiento por escrito",
      description: "El procurador informa al abogado a cargo del movimiento por escrito.",
      agentId: "procurador",
      type: "task",
      nextSteps: [{ targetId: "rv-complejidad" }],
    },
    {
      id: "rv-complejidad",
      label: "Determinar complejidad",
      description: "Se determina quién realiza la gestión según la complejidad del trámite.",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "Mero trámite", targetId: "rv-procurador-gestion" },
        { label: "Complejo", targetId: "rv-abogado-tramite" },
      ],
    },
    {
      id: "rv-procurador-gestion",
      label: "Procurador realiza gestión",
      description: "Se indica al procurador la gestión a realizar, estableciendo plazo menor a 24 horas. Presenta gestión con timbre de tribunal.",
      agentId: "procurador",
      type: "task",
      nextSteps: [{ targetId: "rv-tribunal" }],
    },
    {
      id: "rv-abogado-tramite",
      label: "Abogado realiza trámite",
      description: "El abogado a cargo realiza el trámite dentro del plazo establecido.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rv-tribunal" }],
    },
    {
      id: "rv-tribunal",
      label: "¿Presentarse en tribunal?",
      description: "Se determina si el trámite requiere presentarse físicamente en el tribunal.",
      agentId: "abogado",
      type: "decision",
      nextSteps: [
        { label: "Sí", targetId: "rv-enviar-tribunal" },
        { label: "No (electrónico)", targetId: "rv-electronico" },
      ],
    },
    {
      id: "rv-enviar-tribunal",
      label: "Enviar a Procurador al tribunal",
      description: "Se envía al Procurador a entregar la gestión al tribunal.",
      agentId: "procurador",
      type: "task",
      nextSteps: [{ targetId: "rv-contactar" }],
    },
    {
      id: "rv-electronico",
      label: "Enviar por medio electrónico",
      description: "Se envía el trámite por medio electrónico al tribunal.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rv-contactar" }],
    },
    {
      id: "rv-contactar",
      label: "Contactar cliente e informar",
      description: "El abogado contacta al cliente e informa de la nueva gestión realizada. Se guarda información en ficha del cliente.",
      agentId: "abogado",
      type: "task",
      nextSteps: [{ targetId: "rv-end" }],
    },
    {
      id: "rv-end",
      label: "Fin gestión",
      description: "Revisión diaria de la causa completada.",
      agentId: "abogado",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* 10. LEGALBOT SCRAPER                                                */
/* ================================================================== */
export const legalbotScraperProcess: ProcessDefinition = {
  id: "legalbot-scraper",
  name: "LegalBOT Scraper",
  description: "Proceso automatizado de búsqueda de causas en tribunales vía LegalBOT",
  agents: [
    {
      id: "agente-comercial",
      name: "Agente Comercial",
      role: "agente_comercial",
      color: "teal",
      description: "Configura búsquedas y selecciona causas potenciales",
    },
    {
      id: "bot-scraper",
      name: "Bot Scraper",
      role: "secretaria",
      color: "slate",
      description: "Ejecuta búsquedas automatizadas en juzgados de policía local",
    },
  ],
  steps: [
    {
      id: "lb-start",
      label: "Configurar búsqueda",
      description: "El agente comercial configura los parámetros de búsqueda (tribunal, tipo de causa, fecha).",
      agentId: "agente-comercial",
      type: "start",
      nextSteps: [{ targetId: "lb-ejecutar" }],
    },
    {
      id: "lb-ejecutar",
      label: "Ejecutar scraping",
      description: "El bot ejecuta la búsqueda automatizada en los juzgados de policía local seleccionados.",
      agentId: "bot-scraper",
      type: "task",
      nextSteps: [{ targetId: "lb-resultados" }],
    },
    {
      id: "lb-resultados",
      label: "Procesar resultados",
      description: "Se procesan los resultados encontrados y se filtran las causas relevantes.",
      agentId: "bot-scraper",
      type: "task",
      nextSteps: [{ targetId: "lb-revisar" }],
    },
    {
      id: "lb-revisar",
      label: "Revisar causas encontradas",
      description: "El agente comercial revisa las causas encontradas y selecciona las potencialmente interesantes.",
      agentId: "agente-comercial",
      type: "task",
      nextSteps: [{ targetId: "lb-derivar" }],
    },
    {
      id: "lb-derivar",
      label: "Derivar a proceso JPL",
      description: "Las causas seleccionadas se derivan al proceso de Causas JPL para contactar al cliente.",
      agentId: "agente-comercial",
      type: "subprocess",
      nextSteps: [{ targetId: "lb-end" }],
    },
    {
      id: "lb-end",
      label: "Fin",
      description: "Ciclo de scraping completado.",
      agentId: "bot-scraper",
      type: "end",
    },
  ],
};

/* ================================================================== */
/* MAP OF ALL PROCESSES                                                */
/* ================================================================== */
export const ALL_PROCESSES: Record<string, ProcessDefinition> = {
  "leads": recepcionVisitaProcess,
  "leads-telefono": recepcionTelefonoProcess,
  "proposals": seguimientoPropuestasProcess,
  "contracts": contratoMandatoProcess,
  "notary": documentosNotarialesProcess,
  "email-tickets": respuestaCorreosProcess,
  "collections": procesoCobranzaProcess,
  "matters": causasJPLProcess,
  "case-review": revisionCausasProcess,
  "scraper": legalbotScraperProcess,
};

/* Process mapped to page route */
export const PROCESS_BY_ROUTE: Record<string, ProcessDefinition[]> = {
  "/leads": [recepcionVisitaProcess, recepcionTelefonoProcess],
  "/proposals": [seguimientoPropuestasProcess],
  "/contracts": [contratoMandatoProcess],
  "/notary": [documentosNotarialesProcess],
  "/email-tickets": [respuestaCorreosProcess],
  "/collections": [procesoCobranzaProcess],
  "/matters": [causasJPLProcess],
  "/case-review": [revisionCausasProcess],
  "/scraper": [legalbotScraperProcess],
};
